#!/usr/bin/env bash
# firewall redirects port 8080/TCP to port 80/TCP

sudo nano /etc/ufw/before.rules
*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT
sudo ufw disable
sudo ufw enable
netstat -lpn
